// Builds the web UI's images (src/ui/assets/) and embeds them as base64 in src/ui/assets.gen.ts, so `GET /assets/ui/:name`
// works under `mastra dev` and in the esbuild bundle for Neon alike (no static files to ship).
//   npx tsx scripts/ui-assets.ts            # embed src/ui/assets/* (re-creates missing files from SOURCES first)
//   npx tsx scripts/ui-assets.ts --force    # re-download and re-compress every photo
// Photos are resized to 600×734 and compressed to WebP with ffmpeg (libwebp). Keep the total under ~400 KB.
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { extname, join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const outDir = join(root, 'src/ui/assets');
const genFile = join(root, 'src/ui/assets.gen.ts');
const force = process.argv.includes('--force');
const unsplash = (id: string) => `https://images.unsplash.com/photo-${id}?fm=jpg&q=85&w=900&h=1100&fit=crop`;

/** name → source. `photo` entries are card fallbacks (one per category group, see CATEGORY_PHOTO in src/ui/onboard.ts). */
const SOURCES: { name: string; from: string; photo?: boolean }[] = [
  { name: 'capy-head.webp', from: 'design/homepage/img/capy-head.webp' },
  { name: 'capy-soft.webp', from: 'design/homepage/img/capy-soft.webp' },
  { name: 'favicon.ico', from: 'design/homepage/img/favicon.ico' },
  { name: 'apple-touch-icon.png', from: 'design/homepage/img/apple-touch-icon.png' },
  // Unsplash (free licence), chosen without identifiable performers, like the homepage.
  { name: 'music.webp', from: 'design/homepage/img/green-crowd.jpg', photo: true },
  { name: 'crowd.webp', from: 'design/homepage/img/crowd.jpg', photo: true },
  { name: 'comedy.webp', from: 'design/homepage/img/comedy.jpg', photo: true },
  { name: 'club.webp', from: 'design/homepage/img/club.jpg', photo: true },
  { name: 'market.webp', from: 'design/homepage/img/pumpkins.jpg', photo: true },
  { name: 'film.webp', from: unsplash('1774619755413-7c31ab3aabc3'), photo: true },     // empty cinema, projector beam
  { name: 'theatre.webp', from: unsplash('1688269910489-7fd39ab875eb'), photo: true },  // auditorium, red curtain
  { name: 'art.webp', from: unsplash('1769117619707-4b3446365845'), photo: true },      // gallery, one visitor
  { name: 'talk.webp', from: unsplash('1765323081951-ef6f982a50a8'), photo: true },     // bookshop at night
];

const TYPES: Record<string, string> = { '.webp': 'image/webp', '.png': 'image/png', '.ico': 'image/x-icon', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml' };

await mkdir(outDir, { recursive: true });
const tmp = join(tmpdir(), 'ui-assets');
await mkdir(tmp, { recursive: true });

for (const s of SOURCES) {
  const dest = join(outDir, s.name);
  if (existsSync(dest) && !force) continue;
  let src = join(root, s.from);
  if (s.from.startsWith('http')) {
    src = join(tmp, s.name.replace(/\.\w+$/, '.jpg'));
    const res = await fetch(s.from);
    if (!res.ok) throw new Error(`${s.name}: ${res.status} from ${s.from}`);
    await writeFile(src, Buffer.from(await res.arrayBuffer()));
  }
  if (s.photo) {
    execFileSync('ffmpeg', ['-y', '-v', 'error', '-i', src, '-vf', 'scale=600:734:force_original_aspect_ratio=increase:flags=lanczos,crop=600:734',
      '-c:v', 'libwebp', '-quality', '68', '-compression_level', '6', dest]);
  } else {
    await copyFile(src, dest);
  }
  console.log('built', s.name);
}
await rm(tmp, { recursive: true, force: true });

const files = (await readdir(outDir)).filter(f => TYPES[extname(f)]).sort();
let total = 0;
const entries: string[] = [];
for (const f of files) {
  const buf = await readFile(join(outDir, f));
  total += buf.length;
  const v = createHash('sha1').update(buf).digest('hex').slice(0, 8);
  entries.push(`  ${JSON.stringify(f)}: { type: ${JSON.stringify(TYPES[extname(f)])}, v: '${v}', b64: '${buf.toString('base64')}' },`);
  console.log(`${f.padEnd(24)} ${(buf.length / 1024).toFixed(1).padStart(6)} KB`);
}
await writeFile(
  genFile,
  `// Generated by scripts/ui-assets.ts from src/ui/assets/. Do not edit.\n` +
    `export const ASSETS: Record<string, { type: string; v: string; b64: string }> = {\n${entries.join('\n')}\n};\n`,
);
console.log(`${files.length} files, ${(total / 1024).toFixed(1)} KB → src/ui/assets.gen.ts`);
