import {Easing, interpolate, spring, type SpringConfig} from 'remotion';

export const FPS = 30;
export const TOTAL = 726; // 24.2 s: six voiceover lines plus a 1 s hold after the last word

// Absolute frame marks. Scenes overlap during their hand-rolled transitions. Each voiceover line (vo.*) starts a beat
// after its scene's moment and its speech ends before the next scene's transition starts (see Soundtrack.tsx).
export const T = {
  // 1. headline + capybara
  headline: 3,
  capyPop: 22,
  // 1 -> 2: headline lifts away, the calendar rises, the capybara walks onto it (shared element)
  toWeek: 76,
  // 2. the week ("...and fills them" lands on the fill)
  weekCaption: 82,
  scan: 110,
  fill: 178,
  hop: 192,
  bubble: 196,
  note: 200,
  // 2 -> 3: the dark band slides up over the week
  toPicks: 240,
  // 3. taste
  cards: 250,
  picksHead: 254,
  drag: 290,
  fly: 304,
  // 3 -> 4: paper slides back up over the band
  toBudget: 340,
  // 4. budget ("...and asks before anything bigger" lands on the ask)
  budgetHead: 354,
  step: 372,
  ask: 452,
  booked: 486,
  coin: 494,
  roll: 516,
  // 4 -> 5: camera pans right to the phone
  toPhone: 528,
  // 5. WhatsApp
  typing1: 544,
  msg1: 552,
  reply: 572,
  typing2: 577,
  msg2: 584,
  // 5 -> 6: the phone body grows into the closing card
  toClose: 604,
  closeHead: 616,
  closeCapy: 620,
  logo: 628,
  button: 634,
};

// Voiceover start frames (clips in public/vo/intro-*.mp3, generated by `node scripts/vo.mjs --set intro`)
export const VO = [
  {id: 'intro-1-hero', at: 6},
  {id: 'intro-2-week', at: 84},
  {id: 'intro-3-taste', at: 256},
  {id: 'intro-4-budget', at: 356},
  {id: 'intro-5-whatsapp', at: 537},
  {id: 'intro-6-close', at: 610},
] as const;

export const clamp = {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const;
export const ease = Easing.bezier(0.2, 0.8, 0.2, 1); // the page's .fill curve
export const inOut = Easing.bezier(0.7, 0, 0.25, 1);
export const outCubic = Easing.bezier(0.33, 1, 0.68, 1);

export const lerp = (f: number, [a, b]: [number, number], [x, y]: [number, number], easing = ease) =>
  interpolate(f, [a, b], [x, y], {...clamp, easing});

export const sp = (f: number, start: number, config: Partial<SpringConfig> = {}, durationInFrames?: number) =>
  spring({frame: f - start, fps: FPS, config: {damping: 200, ...config}, durationInFrames});

export const mix = (p: number, a: number, b: number) => a + (b - a) * p;
