const data=JSON.parse(document.getElementById('variants').textContent);
const root=document.getElementById('gallery');
const src=(id,file)=>`assets/${id}/${file}`;
root.innerHTML=data.map((v,i)=>`<article class="card" id="${v.id}"><div class="stage"><span class="badge">0${i+1} / ${v.kind}</span><img src="${src(v.id,'preview.webp')}" alt="Mellow capybara: ${v.name}" width="400" height="400"></div><div class="content"><div class="title"><h2>${v.name}</h2><button class="choose" data-id="${v.id}" aria-label="Compare ${v.name}" aria-pressed="false">Compare</button></div><p>${v.note}</p><div class="scales">${[16,24,32,48,64].map(s=>`<div class="scale"><img src="${src(v.id,`favicon-${s}.png`)}" width="${s}" height="${s}" alt="${v.name} at ${s}px"><span>${s}px</span></div>`).join('')}</div><div class="tabs"><div class="tab"><img src="${src(v.id,'favicon-16.png')}" alt="">mellow <span aria-hidden="true">×</span></div><div class="tab dark"><img src="${src(v.id,'favicon-16.png')}" alt="">mellow <span aria-hidden="true">×</span></div></div><div class="use">${v.use}</div><div class="downloads"><a href="${src(v.id,'mascot.png')}" download="mellow-${v.id}.png">Mascot PNG ↓</a><a href="${src(v.id,'favicon.ico')}" download="mellow-${v.id}.ico">Favicon ICO ↓</a></div></div></article>`).join('');
let chosen=data[2];
function select(id){chosen=data.find(v=>v.id===id);document.getElementById('chosen-hero').src=src(id,'preview.webp');document.getElementById('chosen-hero').alt=chosen.name+' Mellow mascot';document.getElementById('chosen-name').textContent=chosen.name;document.getElementById('chosen-kind').textContent=chosen.kind;document.getElementById('chosen-note').textContent=chosen.note;document.getElementById('chosen-label').textContent=chosen.name;document.getElementById('chosen-size').src=src(id,'preview.webp');document.getElementById('nav-icon').src=src(id,'favicon-32.png');document.getElementById('page-icon').href=src(id,'favicon-32.png');for(const b of document.querySelectorAll('.choose')){const on=b.dataset.id===id;b.setAttribute('aria-pressed',String(on));b.textContent=on?'Selected ✓':'Compare';b.closest('.card').classList.toggle('selected',on);}document.getElementById('status').textContent=chosen.name+' selected in comparison';}
root.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)select(b.dataset.id)});
const slider=document.getElementById('size');function resize(){document.getElementById('size-label').value=slider.value+'px';for(const im of document.querySelectorAll('.sizeimg')){im.style.width=slider.value+'px';im.style.height=slider.value+'px';}}
slider.addEventListener('input',resize);
for(const b of document.querySelectorAll('.bgbtn'))b.addEventListener('click',()=>{document.documentElement.style.setProperty('--surface',b.dataset.color);for(const x of document.querySelectorAll('.bgbtn'))x.setAttribute('aria-pressed',String(x===b));});
select(chosen.id);resize();
