import fs from 'node:fs/promises';
const dir=new URL('./',import.meta.url);
const variants=await fs.readFile(new URL('variants.json',dir),'utf8');
const css=await fs.readFile(new URL('style.css',dir),'utf8');
const js=await fs.readFile(new URL('app.js',dir),'utf8');
await fs.writeFile(new URL('index.html',dir),`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mellow, with a little less fuss — six mascot refinements</title><link id="page-icon" rel="icon" href="assets/03-flat-face/favicon-32.png"><style>${css}</style></head><body><div class="wrap">
<nav><span class="logo"><img id="nav-icon" src="assets/03-flat-face/favicon-32.png" alt="">mellow</span><div class="navright"><span>Character study / 02</span><a href="../">All original directions ↗</a></div></nav>
<header class="intro"><div><div class="eyebrow">Same little friend. Fewer little details.</div><h1>A familiar face.<br>A little less fuss.</h1></div><p>Six ways to simplify Mellow. Try the faces at actual favicon sizes, compare each with the original, and find the right balance of character and clarity.</p></header>
<section class="audition" aria-label="Compare original and selected variant"><div class="feature"><div><span class="eyebrow" id="chosen-kind">Compact face</span><h2 id="chosen-name">Face icon</h2><p id="chosen-note"></p></div><img id="chosen-hero" src="assets/03-flat-face/preview.webp" alt="Face icon" width="220" height="220"></div><div class="testbench"><h2>The small-size test</h2><p>These are actual CSS pixel sizes. Use the slider to see what survives.</p><label class="sizecontrol" for="size"><span>Size</span><input id="size" type="range" min="16" max="96" step="8" value="32"><output id="size-label" for="size">32px</output></label><div class="compare"><div class="samplebox"><img class="sizeimg" src="../assets/01-mellow/preview.webp" alt="Original Mellow at selected size"><span>Original</span></div><div class="samplebox"><img class="sizeimg" id="chosen-size" src="assets/03-flat-face/preview.webp" alt="Selected Mellow variant at selected size"><span id="chosen-label">Face icon</span></div></div></div></section>
<div class="controls" aria-label="Preview background"><strong>Try a background</strong><button class="bgbtn" data-color="#F6EDDC" aria-pressed="true">Oat</button><button class="bgbtn" data-color="#FFFFFF" aria-pressed="false">White</button><button class="bgbtn" data-color="#292522" aria-pressed="false">Dark</button><span id="status" class="status" aria-live="polite"></span></div>
<main class="grid" id="gallery"></main>
<aside class="recommendation"><div><span class="eyebrow">One character, two useful versions</span><p>Use a full-body Mellow where there is room for personality, and a compact face for browser tabs and navigation. The color, ears, and broad muzzle tie them together.</p></div><div><span class="eyebrow">Choose at the size you will use</span><p>Start at 16 or 24px. The clocks are a large-format detail; the face and silhouette should do the work at small sizes. The one-color cocoa mark is intended for light backgrounds.</p></div></aside>
<footer>Six imagegen refinements of the original Mellow. Transparent originals plus PNG favicon sizes and ICO downloads. Images are raster concepts.</footer>
</div><script type="application/json" id="variants">${variants}</script><script>${js}</script></body></html>`);
